# Witaj w configu bota DenoriaBot!
# Tutaj jest miejsce, gdzie możesz podać wszystkie dane, aby bot mógł działać!

# W tym polu wpisz token bota
# *Pamiętaj że token, jest tajny! Nie pokazuj go nikomu!*
token: 